[phases.setup]
nixPkgs = ["nodejs", "chromium", "google-chrome-stable"]

[phases.build]
cmds = ["npm install"]

[environment]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/google-chrome-stable"
