const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');
require('dotenv').config();
const app = express();
app.use(cors());
app.use(express.json());
app.use('/api/v1', require('./routes/filterRoutes'));
mongoose.connect(process.env.MONGODB_URI).then(() => console.log('✅ MongoDB connected')).catch(err => console.error(err));
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`🚀 ELIMFILTERS API v11.0.6 running on port ${PORT}`));
